<#
.SYNOPSIS
    Provisions approved IAM Project 1 joiner requests.

.DESCRIPTION
    Run in Windows PowerShell as Administrator on DC01. The script validates
    the approved request-file digest, request state, managers, OUs, groups and
    identity collisions before its first directory write.

    New accounts are created disabled with unique 24-character passwords
    generated by a cryptographic random-number generator. Password values are
    never displayed, logged or exported. Manager, direct access and contractor
    expiration controls are applied before activation.

    Exact existing identities are evaluated against the desired state. A
    repeated approved request therefore becomes a no-change decision rather
    than a duplicate account or password reset. Unexpected IAM memberships or
    unsafe identity collisions stop execution and are never removed silently.

    If a transaction fails, identities created by that execution are retained
    but safety-disabled for investigation. The script never deletes users,
    groups or OUs.
#>

[CmdletBinding()]
param(
    [string]$CsvPath = 'C:\IAM-Lab\data\iam-project1-joiner-requests.csv',
    [string]$ExpectedSHA256 = '8685B8C4C99B68ED7B7EFAA888587FBDDBF0E94B48932922D130AEDD2B470CEE',
    [string]$ExpectedComputerName = 'DC01',
    [string]$ExpectedDomain = 'corporate.test',
    [string]$UsersRoot = 'OU=Users,OU=IAM-Lab,DC=corporate,DC=test',
    [string]$LeaversOU = 'OU=Leavers,OU=Users,OU=IAM-Lab,DC=corporate,DC=test',
    [string]$LogFolder = 'C:\IAM-Lab\logs'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module ActiveDirectory

$CorrelationID = 'M04-JOINER-{0}' -f (Get-Date -Format 'yyyyMMdd-HHmmss')
$AuditPath = Join-Path $LogFolder "$CorrelationID-audit.csv"
$AuditEvents = New-Object System.Collections.ArrayList
$CreatedSamAccounts = New-Object System.Collections.ArrayList

function Add-AuditEvent {
    [CmdletBinding()]
    param(
        [string]$RequestID,
        [string]$EmployeeID,
        [string]$SamAccountName,
        [string]$Action,
        [string]$Result,
        [string]$Detail
    )

    [void]$AuditEvents.Add([pscustomobject]@{
        TimestampUTC = [datetime]::UtcNow.ToString('o')
        CorrelationID = $CorrelationID
        RequestID = $RequestID
        EmployeeID = $EmployeeID
        SamAccountName = $SamAccountName
        Action = $Action
        Result = $Result
        Detail = $Detail
    })
}

function Get-ApprovedGroups {
    [CmdletBinding()]
    param([Parameter(Mandatory)]$Record)

    return @(
        @($Record.BaselineGroups, $Record.DepartmentGroup, $Record.AccessGroups) |
            ForEach-Object { [string]$_ -split ';' } |
            ForEach-Object { $_.Trim() } |
            Where-Object { $_ } |
            Sort-Object -Unique
    )
}

function New-CryptographicPassword {
    [CmdletBinding()]
    param([ValidateRange(16, 128)][int]$Length = 24)

    $Upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    $Lower = 'abcdefghijkmnopqrstuvwxyz'
    $Digits = '23456789'
    $Symbols = '!@#$%*-_=+'
    $All = $Upper + $Lower + $Digits + $Symbols
    $Provider = [System.Security.Cryptography.RandomNumberGenerator]::Create()

    try {
        $Characters = New-Object System.Collections.Generic.List[char]

        foreach ($Set in @($Upper, $Lower, $Digits, $Symbols)) {
            $Buffer = New-Object byte[] 4
            $Provider.GetBytes($Buffer)
            $Index = [BitConverter]::ToUInt32($Buffer, 0) % $Set.Length
            $Characters.Add($Set[$Index])
        }

        while ($Characters.Count -lt $Length) {
            $Buffer = New-Object byte[] 4
            $Provider.GetBytes($Buffer)
            $Index = [BitConverter]::ToUInt32($Buffer, 0) % $All.Length
            $Characters.Add($All[$Index])
        }

        for ($Index = $Characters.Count - 1; $Index -gt 0; $Index--) {
            $Buffer = New-Object byte[] 4
            $Provider.GetBytes($Buffer)
            $SwapIndex = [BitConverter]::ToUInt32($Buffer, 0) % ($Index + 1)
            $Temporary = $Characters[$Index]
            $Characters[$Index] = $Characters[$SwapIndex]
            $Characters[$SwapIndex] = $Temporary
        }

        return -join $Characters
    }
    finally {
        $Provider.Dispose()
    }
}

if (-not (Test-Path -LiteralPath $LogFolder -PathType Container)) {
    $null = New-Item -Path $LogFolder -ItemType Directory
}

try {
    if ($env:COMPUTERNAME -ne $ExpectedComputerName) {
        throw "Run this script on $ExpectedComputerName, not $env:COMPUTERNAME."
    }

    $Domain = Get-ADDomain

    if ($Domain.DNSRoot -ne $ExpectedDomain) {
        throw "Expected domain $ExpectedDomain but detected $($Domain.DNSRoot)."
    }

    if (-not (Test-Path -LiteralPath $CsvPath -PathType Leaf)) {
        throw "Approved joiner dataset not found at $CsvPath."
    }

    $ActualHash = (Get-FileHash -LiteralPath $CsvPath -Algorithm SHA256).Hash

    if ($ActualHash -ne $ExpectedSHA256) {
        throw "Dataset integrity check failed. Expected $ExpectedSHA256 but calculated $ActualHash."
    }

    $Records = @(Import-Csv -LiteralPath $CsvPath)

    if ($Records.Count -ne 3) {
        throw "Expected exactly three joiner requests but found $($Records.Count)."
    }

    $SecretColumns = @(
        $Records[0].PSObject.Properties.Name |
            Where-Object { $_ -match '(?i)password|secret|credential|token' }
    )

    if ($SecretColumns.Count -ne 0) {
        throw "Prohibited secret-bearing columns detected: $($SecretColumns -join ', ')."
    }

    foreach ($PropertyName in @('RequestID', 'EmployeeID', 'SamAccountName', 'UserPrincipalName')) {
        $Duplicates = @(
            $Records |
                Group-Object -Property $PropertyName |
                Where-Object Count -gt 1
        )

        if ($Duplicates.Count -ne 0) {
            throw "The joiner dataset contains duplicate $PropertyName values."
        }
    }

    $InvalidRequests = @(
        $Records |
            Where-Object {
                $_.RequestType -ne 'Joiner' -or
                $_.ApprovalStatus -ne 'Approved' -or
                $_.LifecycleStatus -ne 'Active' -or
                ([datetime]$_.StartDate).Date -gt (Get-Date).Date
            }
    )

    if ($InvalidRequests.Count -ne 0) {
        throw "$($InvalidRequests.Count) request records are not approved and date-eligible."
    }

    $WorkItems = New-Object System.Collections.ArrayList
    $TotalApprovedMemberships = 0

    foreach ($Record in $Records) {
        $EscapedManagerID = $Record.ManagerEmployeeID.Replace("'", "''")
        $Manager = @(
            Get-ADUser `
                -Filter "EmployeeID -eq '$EscapedManagerID'" `
                -Properties EmployeeID, Enabled
        )

        if ($Manager.Count -ne 1 -or -not $Manager[0].Enabled) {
            throw "Manager $($Record.ManagerEmployeeID) is missing, duplicated or disabled."
        }

        $null = Get-ADOrganizationalUnit -Identity $Record.TargetOU
        $ApprovedGroups = New-Object System.Collections.ArrayList

        foreach ($GroupName in @(Get-ApprovedGroups -Record $Record)) {
            $Group = Get-ADGroup `
                -Identity $GroupName `
                -Properties GroupCategory, GroupScope

            if ($Group.GroupCategory -ne 'Security' -or $Group.GroupScope -ne 'Global') {
                throw "$GroupName is not a Global Security group."
            }

            [void]$ApprovedGroups.Add($Group)
        }

        $TotalApprovedMemberships += $ApprovedGroups.Count
        $EscapedEmployeeID = $Record.EmployeeID.Replace("'", "''")
        $EscapedSam = $Record.SamAccountName.Replace("'", "''")
        $EscapedUPN = $Record.UserPrincipalName.Replace("'", "''")
        $Matches = @(
            Get-ADUser `
                -Filter "EmployeeID -eq '$EscapedEmployeeID' -or SamAccountName -eq '$EscapedSam' -or UserPrincipalName -eq '$EscapedUPN'" `
                -Properties EmployeeID, UserPrincipalName, GivenName, Surname,
                    DisplayName, Department, Title, Company, Mail, employeeType,
                    Description, Manager, MemberOf, Enabled, AccountExpirationDate
        )

        if ($Matches.Count -gt 1) {
            throw "Multiple existing identities collide with request $($Record.RequestID)."
        }

        $ExistingUser = $null

        if ($Matches.Count -eq 1) {
            $ExistingUser = $Matches[0]
            $ExactIdentityMatch = (
                $ExistingUser.EmployeeID -eq $Record.EmployeeID -and
                $ExistingUser.SamAccountName -eq $Record.SamAccountName -and
                $ExistingUser.UserPrincipalName -eq $Record.UserPrincipalName
            )

            if (-not $ExactIdentityMatch) {
                throw "An unsafe identity collision exists for request $($Record.RequestID)."
            }

            $CurrentParentOU = $ExistingUser.DistinguishedName.Substring(
                $ExistingUser.DistinguishedName.IndexOf(',') + 1
            )

            if ($CurrentParentOU -ne $Record.TargetOU) {
                throw "$($Record.SamAccountName) exists outside its approved target OU."
            }

            $ExpectedGroupDNs = @($ApprovedGroups.DistinguishedName)
            $CurrentIAMGroupDNs = @(
                $ExistingUser.MemberOf |
                    Where-Object { $_ -like 'CN=GG_IAM_*' }
            )
            $UnexpectedIAMGroups = @(
                $CurrentIAMGroupDNs |
                    Where-Object { $_ -notin $ExpectedGroupDNs }
            )

            if ($UnexpectedIAMGroups.Count -ne 0) {
                throw "$($Record.SamAccountName) has unexpected IAM memberships; none were removed."
            }
        }

        [void]$WorkItems.Add([pscustomobject]@{
            Record = $Record
            Manager = $Manager[0]
            ApprovedGroups = @($ApprovedGroups)
            ExistingUser = $ExistingUser
        })
    }

    if ($TotalApprovedMemberships -ne 13) {
        throw "Expected 13 approved memberships but calculated $TotalApprovedMemberships."
    }

    Add-AuditEvent `
        -RequestID 'DATASET' `
        -EmployeeID '' `
        -SamAccountName '' `
        -Action 'PreflightValidation' `
        -Result 'Success' `
        -Detail 'Approved dataset hash, requests, managers, OUs, groups, and collisions validated.'

    $CreatedUserCount = 0
    $UpdatedUserCount = 0
    $NoOpUserCount = 0
    $ManagerAssignmentsMade = 0
    $MembershipsAdded = 0
    $AccountsEnabled = 0
    $ContractorExpirationsApplied = 0

    foreach ($Item in $WorkItems) {
        $Record = $Item.Record
        $User = $Item.ExistingUser
        $ItemChanged = $false

        if ($null -eq $User) {
            $PlainPassword = New-CryptographicPassword -Length 24

            try {
                $SecurePassword = ConvertTo-SecureString $PlainPassword -AsPlainText -Force
                New-ADUser `
                    -Name $Record.DisplayName `
                    -GivenName $Record.GivenName `
                    -Surname $Record.Surname `
                    -DisplayName $Record.DisplayName `
                    -SamAccountName $Record.SamAccountName `
                    -UserPrincipalName $Record.UserPrincipalName `
                    -EmailAddress $Record.UserPrincipalName `
                    -EmployeeID $Record.EmployeeID `
                    -Department $Record.Department `
                    -Title $Record.JobTitle `
                    -Company 'Corporate Test' `
                    -Description "IAM Project 1 | Joiner | $($Record.WorkerType) | Staged | $($Record.RequestID)" `
                    -Path $Record.TargetOU `
                    -AccountPassword $SecurePassword `
                    -Enabled $false `
                    -PasswordNeverExpires $false `
                    -CannotChangePassword $false `
                    -OtherAttributes @{ employeeType = $Record.WorkerType }
            }
            finally {
                $PlainPassword = $null
                $SecurePassword = $null
            }

            [void]$CreatedSamAccounts.Add($Record.SamAccountName)
            $CreatedUserCount++
            $ItemChanged = $true
            Add-AuditEvent `
                -RequestID $Record.RequestID `
                -EmployeeID $Record.EmployeeID `
                -SamAccountName $Record.SamAccountName `
                -Action 'CreateDisabledAccount' `
                -Result 'Success' `
                -Detail 'Account created in disabled staging state. Password was not logged or exported.'

            $User = Get-ADUser `
                -Identity $Record.SamAccountName `
                -Properties EmployeeID, UserPrincipalName, GivenName, Surname,
                    DisplayName, Department, Title, Company, Mail, employeeType,
                    Description, Manager, MemberOf, Enabled, AccountExpirationDate
        }
        else {
            $AttributeChanges = @{}
            $FinalDescription = "IAM Project 1 | Joiner | $($Record.WorkerType) | Active | $($Record.RequestID)"
            $AttributeMap = @{
                givenName = $Record.GivenName
                sn = $Record.Surname
                displayName = $Record.DisplayName
                department = $Record.Department
                title = $Record.JobTitle
                company = 'Corporate Test'
                mail = $Record.UserPrincipalName
                employeeType = $Record.WorkerType
                description = $FinalDescription
            }
            $CurrentMap = @{
                givenName = $User.GivenName
                sn = $User.Surname
                displayName = $User.DisplayName
                department = $User.Department
                title = $User.Title
                company = $User.Company
                mail = $User.Mail
                employeeType = $User.employeeType
                description = $User.Description
            }

            foreach ($AttributeName in $AttributeMap.Keys) {
                if ($CurrentMap[$AttributeName] -ne $AttributeMap[$AttributeName]) {
                    $AttributeChanges[$AttributeName] = $AttributeMap[$AttributeName]
                }
            }

            if ($AttributeChanges.Count -gt 0) {
                Set-ADUser -Identity $User -Replace $AttributeChanges
                $UpdatedUserCount++
                $ItemChanged = $true
                Add-AuditEvent `
                    -RequestID $Record.RequestID `
                    -EmployeeID $Record.EmployeeID `
                    -SamAccountName $Record.SamAccountName `
                    -Action 'ReconcileAttributes' `
                    -Result 'Success' `
                    -Detail "$($AttributeChanges.Count) approved attributes reconciled."
            }
        }

        $User = Get-ADUser `
            -Identity $Record.SamAccountName `
            -Properties Manager, MemberOf, Enabled, AccountExpirationDate, Description

        if ($User.Manager -ne $Item.Manager.DistinguishedName) {
            Set-ADUser -Identity $User -Manager $Item.Manager.DistinguishedName
            $ManagerAssignmentsMade++
            $ItemChanged = $true
            Add-AuditEvent `
                -RequestID $Record.RequestID `
                -EmployeeID $Record.EmployeeID `
                -SamAccountName $Record.SamAccountName `
                -Action 'AssignManager' `
                -Result 'Success' `
                -Detail "Approved manager $($Record.ManagerEmployeeID) assigned."
        }

        if ($Record.WorkerType -eq 'Contractor') {
            if ([string]::IsNullOrWhiteSpace($Record.EndDate)) {
                throw "Contractor $($Record.EmployeeID) has no approved EndDate."
            }

            $RequiredExpiration = ([datetime]$Record.EndDate).Date.AddDays(1)

            if ($null -eq $User.AccountExpirationDate -or $User.AccountExpirationDate.Date -ne $RequiredExpiration) {
                Set-ADAccountExpiration -Identity $User -DateTime $RequiredExpiration
                $ContractorExpirationsApplied++
                $ItemChanged = $true
                Add-AuditEvent `
                    -RequestID $Record.RequestID `
                    -EmployeeID $Record.EmployeeID `
                    -SamAccountName $Record.SamAccountName `
                    -Action 'ApplyContractExpiration' `
                    -Result 'Success' `
                    -Detail "Account expiration applied for $($RequiredExpiration.ToString('yyyy-MM-dd'))."
            }
        }

        $CurrentMemberships = @(
            (Get-ADUser -Identity $User -Properties MemberOf).MemberOf
        )

        foreach ($Group in $Item.ApprovedGroups) {
            if ($Group.DistinguishedName -notin $CurrentMemberships) {
                Add-ADGroupMember -Identity $Group -Members $User
                $MembershipsAdded++
                $ItemChanged = $true
                Add-AuditEvent `
                    -RequestID $Record.RequestID `
                    -EmployeeID $Record.EmployeeID `
                    -SamAccountName $Record.SamAccountName `
                    -Action 'AddApprovedMembership' `
                    -Result 'Success' `
                    -Detail "Added to $($Group.SamAccountName)."
            }
        }

        $User = Get-ADUser -Identity $User -Properties Enabled, Description

        if (-not $User.Enabled) {
            Enable-ADAccount -Identity $User
            $AccountsEnabled++
            $ItemChanged = $true
            Add-AuditEvent `
                -RequestID $Record.RequestID `
                -EmployeeID $Record.EmployeeID `
                -SamAccountName $Record.SamAccountName `
                -Action 'EnableApprovedAccount' `
                -Result 'Success' `
                -Detail 'Account enabled after all approved controls were applied.'
        }

        $FinalDescription = "IAM Project 1 | Joiner | $($Record.WorkerType) | Active | $($Record.RequestID)"

        if ($User.Description -ne $FinalDescription) {
            Set-ADUser -Identity $User -Description $FinalDescription
            $ItemChanged = $true
        }

        if (-not $ItemChanged) {
            $NoOpUserCount++
            Add-AuditEvent `
                -RequestID $Record.RequestID `
                -EmployeeID $Record.EmployeeID `
                -SamAccountName $Record.SamAccountName `
                -Action 'IdempotentReplay' `
                -Result 'NoChange' `
                -Detail 'Existing identity already matched the approved desired state.'
        }
    }

    $ControlledUsers = @(
        Get-ADUser `
            -SearchBase $UsersRoot `
            -LDAPFilter '(objectCategory=person)' `
            -Properties Enabled, employeeType, Manager, MemberOf,
                EmployeeID, AccountExpirationDate
    )
    $EnabledUsers = @($ControlledUsers | Where-Object Enabled)
    $Employees = @($ControlledUsers | Where-Object employeeType -eq 'Employee')
    $Contractors = @($ControlledUsers | Where-Object employeeType -eq 'Contractor')
    $ManagerAssigned = @($ControlledUsers | Where-Object { $null -ne $_.Manager })
    $TotalDirectMemberships = (
        $ControlledUsers |
            ForEach-Object {
                @($_.MemberOf | Where-Object { $_ -like 'CN=GG_IAM_*' }).Count
            } |
            Measure-Object -Sum
    ).Sum
    $LeaverUserCount = @(
        Get-ADUser -SearchBase $LeaversOU -SearchScope OneLevel -Filter *
    ).Count
    $ContractorExpirationFailures = 0

    foreach ($Record in @($Records | Where-Object WorkerType -eq 'Contractor')) {
        $Contractor = Get-ADUser `
            -Identity $Record.SamAccountName `
            -Properties AccountExpirationDate
        $ExpectedExpiration = ([datetime]$Record.EndDate).Date.AddDays(1)

        if ($null -eq $Contractor.AccountExpirationDate -or $Contractor.AccountExpirationDate.Date -ne $ExpectedExpiration) {
            $ContractorExpirationFailures++
        }
    }

    $PermanentEmployeeCount = @(
        Get-ADGroupMember -Identity 'GG_All_Employees' -Recursive
    ).Count
    $IDTRUsers = @(
        Get-ADUser -Filter "SamAccountName -like 'idtr-user*'" -Properties Enabled
    )
    $IDTRDisabledCount = @($IDTRUsers | Where-Object { -not $_.Enabled }).Count
    $HighValueGroupMembers = @(
        Get-ADGroupMember -Identity 'IDTR-HighValue-Lab'
    ).Count

    $Passed = (
        $ControlledUsers.Count -eq 33 -and
        $EnabledUsers.Count -eq 33 -and
        $Employees.Count -eq 27 -and
        $Contractors.Count -eq 6 -and
        $ManagerAssigned.Count -eq 27 -and
        $TotalDirectMemberships -eq 153 -and
        $LeaverUserCount -eq 0 -and
        $ContractorExpirationFailures -eq 0 -and
        $PermanentEmployeeCount -eq 50 -and
        $IDTRUsers.Count -eq 5 -and
        $IDTRDisabledCount -eq 5 -and
        $HighValueGroupMembers -eq 0
    )

    if (-not $Passed) {
        throw 'Post-provisioning identity validation did not reach the approved state.'
    }

    Add-AuditEvent `
        -RequestID 'TRANSACTION' `
        -EmployeeID '' `
        -SamAccountName '' `
        -Action 'PostProvisioningValidation' `
        -Result 'Success' `
        -Detail 'All approved joiner totals and isolation controls validated.'

    $AuditEvents |
        Export-Csv -LiteralPath $AuditPath -NoTypeInformation -Encoding UTF8

    [pscustomobject]@{
        ComputerName = $env:COMPUTERNAME
        CorrelationID = $CorrelationID
        DatasetHashMatches = ($ActualHash -eq $ExpectedSHA256)
        ApprovedJoinerCount = $Records.Count
        CreatedUserCount = $CreatedUserCount
        UpdatedUserCount = $UpdatedUserCount
        NoOpUserCount = $NoOpUserCount
        ManagerAssignmentsMade = $ManagerAssignmentsMade
        MembershipsAdded = $MembershipsAdded
        AccountsEnabled = $AccountsEnabled
        ContractorExpirationsApplied = $ContractorExpirationsApplied
        ControlledUserCount = $ControlledUsers.Count
        EnabledUserCount = $EnabledUsers.Count
        EmployeeCount = $Employees.Count
        ContractorCount = $Contractors.Count
        ManagerAssignedCount = $ManagerAssigned.Count
        TotalDirectMemberships = $TotalDirectMemberships
        LeaverUserCount = $LeaverUserCount
        ContractorExpirationFailures = $ContractorExpirationFailures
        PermanentEmployeeCount = $PermanentEmployeeCount
        IDTRUserCount = $IDTRUsers.Count
        IDTRDisabledCount = $IDTRDisabledCount
        HighValueGroupMembers = $HighValueGroupMembers
        AuditLogPath = $AuditPath
        AuditEventCount = $AuditEvents.Count
        PasswordsDisplayedOrExported = $false
    } | Format-List

    Write-Host ''
    Write-Host 'PASS: All three approved joiners were provisioned, governed, audited, and validated successfully.' -ForegroundColor Green
}
catch {
    $FailureMessage = $_.Exception.Message

    foreach ($SamAccountName in $CreatedSamAccounts) {
        try {
            Disable-ADAccount -Identity $SamAccountName
            Add-AuditEvent `
                -RequestID 'TRANSACTION' `
                -EmployeeID '' `
                -SamAccountName $SamAccountName `
                -Action 'SafetyDisable' `
                -Result 'Success' `
                -Detail 'Account disabled after the transaction encountered an error.'
        }
        catch {
            # Preserve the original transaction error.
        }
    }

    Add-AuditEvent `
        -RequestID 'TRANSACTION' `
        -EmployeeID '' `
        -SamAccountName '' `
        -Action 'TransactionFailure' `
        -Result 'Failed' `
        -Detail $FailureMessage

    try {
        $AuditEvents |
            Export-Csv -LiteralPath $AuditPath -NoTypeInformation -Encoding UTF8
    }
    catch {
        # Preserve the original transaction error if audit export also fails.
    }

    Write-Host ''
    Write-Host 'FAIL: Joiner provisioning stopped. Accounts created during this run were retained but disabled.' -ForegroundColor Red
    Write-Host "Audit log: $AuditPath" -ForegroundColor Yellow
    throw
}
